const translations = {
    en: {
        welcomeTitle: "Welcome to Mimic Launcher",
        username: "Username:",
        usernamePlaceholder: "Enter your Minecraft username",
        gameVersion: "Game Version:",
        modLoader: "Mod Loader:",
        launchGame: "Launch Game",
        settings: "Settings",
        gameDirectory: "Game Directory:",
        gameDirectoryPlaceholder: "Enter game directory",
        defaultButton: "Default",
        openButton: "Open",
        selectPathButton: "Select Path",
        javaPath: "Java Path:",
        javaPathPlaceholder: "Enter Java path",
        memoryAllocation: "Memory Allocation (GB):",
        jvmArguments: "JVM Arguments:",
        jvmArgumentsPlaceholder: "Enter JVM arguments",
        language: "Language:",
        enableAutoUpdates: "Enable Auto Updates",
        showAlphaVersions: "Show Alpha Versions",
        saveSettings: "Save Settings",
        mods: "Mods",
        searchMods: "Search Mods:",
        searchModsPlaceholder: "Search for mods",
        installMods: "Install Selected Mods",
    },
    ru: {
        welcomeTitle: "Добро пожаловать в Mimic Launcher",
        username: "Имя пользователя:",
        usernamePlaceholder: "Введите ваше имя в Minecraft",
        gameVersion: "Версия игры:",
        modLoader: "Загрузчик модов:",
        launchGame: "Запустить игру",
        settings: "Настройки",
        gameDirectory: "Директория игры:",
        gameDirectoryPlaceholder: "Введите директорию игры",
        defaultButton: "По умолчанию",
        openButton: "Открыть",
        selectPathButton: "Выбрать путь",
        javaPath: "Путь к Java:",
        javaPathPlaceholder: "Введите путь к Java",
        memoryAllocation: "Выделение памяти (ГБ):",
        jvmArguments: "Аргументы JVM:",
        jvmArgumentsPlaceholder: "Введите аргументы JVM",
        language: "Язык:",
        enableAutoUpdates: "Включить автообновления",
        showAlphaVersions: "Показывать альфа-версии",
        saveSettings: "Сохранить настройки",
        mods: "Моды",
        searchMods: "Поиск модов:",
        searchModsPlaceholder: "Поиск модов",
        installMods: "Установить выбранные моды",
    },
    de: {
        welcomeTitle: "Willkommen beim Mimic Launcher",
        username: "Benutzername:",
        usernamePlaceholder: "Geben Sie Ihren Minecraft-Benutzernamen ein",
        gameVersion: "Spielversion:",
        modLoader: "Mod-Loader:",
        launchGame: "Spiel starten",
        settings: "Einstellungen",
        gameDirectory: "Spielverzeichnis:",
        gameDirectoryPlaceholder: "Spielverzeichnis eingeben",
        defaultButton: "Standard",
        selectPathButton: "Pfad auswählen",
        javaPath: "Java-Pfad:",
        javaPathPlaceholder: "Java-Pfad eingeben",
        memoryAllocation: "Speicherzuweisung (GB):",
        jvmArguments: "JVM-Argumente:",
        jvmArgumentsPlaceholder: "JVM-Argumente eingeben",
        language: "Sprache:",
        enableAutoUpdates: "Automatische Updates aktivieren",
        showAlphaVersions: "Alpha-Versionen anzeigen",
        saveSettings: "Einstellungen speichern",
        mods: "Mods",
        searchMods: "Mods suchen:",
        searchModsPlaceholder: "Nach Mods suchen",
        installMods: "Ausgewählte Mods installieren",
    },
    fr: {
        welcomeTitle: "Bienvenue sur Mimic Launcher",
        username: "Nom d'utilisateur :",
        usernamePlaceholder: "Entrez votre nom d'utilisateur Minecraft",
        gameVersion: "Version du jeu :",
        modLoader: "Chargeur de mods :",
        launchGame: "Lancer le jeu",
        settings: "Paramètres",
        gameDirectory: "Répertoire du jeu :",
        gameDirectoryPlaceholder: "Entrez le répertoire du jeu",
        defaultButton: "Par défaut",
        selectPathButton: "Sélectionner le chemin",
        javaPath: "Chemin Java :",
        javaPathPlaceholder: "Entrez le chemin Java",
        memoryAllocation: "Allocation de mémoire (Go) :",
        jvmArguments: "Arguments JVM :",
        jvmArgumentsPlaceholder: "Entrez les arguments JVM",
        language: "Langue :",
        enableAutoUpdates: "Activer les mises à jour automatiques",
        showAlphaVersions: "Afficher les versions alpha",
        saveSettings: "Enregistrer les paramètres",
        mods: "Mods",
        searchMods: "Rechercher des mods :",
        searchModsPlaceholder: "Rechercher des mods",
        installMods: "Installer les mods sélectionnés",
    },
}